### ISSUE TITLE
USe ethernet/IP variables name

### ISSUE THREAD

**Issue by gepponline** [jmor2000/LV-OMRON-FINS#1]
I'm trying to communicate with an OMRON PLC via ethernet IP using LabVIEW.
Someone suggest me this solution but it's not clear to me if it's possible to read/write values from/to PLC using variables name.
Examples are not clear about it.
using example 1, communication seems to be ok but i can't figure out How to use it to exchange data.

**Comment by jmor2000** [comment]
This example, shows you three key steps which are required to utilise the OMRON FINS TCP protocal, 1. make connection, 2. handshake node IDs, 3. request something. You only do steps 1 & 2 once, and there after you can send any type of FINS Command. A list of commands can be found in FINS "Commands REFERENCE MANUAL". This example only covers read commands, but write commands are very similar, just construct the FINS message, as per the reference manual, and decode it as needed. All the building blocks are there.
![Capture](https://user-images.githubusercontent.com/74370093/164543394-4e9098d1-4ddf-4f71-8593-aff59d25c693.JPG)

**Comment by gepponline** [comment]
Ok, thank you, In the example it's not clear to me which data is requested.
I took a look at the FINS manual but is still not clear how to read or write a simple variable value knowing the variable name :(
I only know variable names 'cause it's a third party PLC where I don't have access to the source code.

**Comment by jmor2000** [comment]
Hopefully this might help (see document link below), otherwise you might want to check out an alternative route, such as trying an industrial middleware (OPC UA server). I beleive NI has one, or you could try a very common third party software (Kepware).

https://github.com/jmor2000/LV-OMRON-FINS/blob/74a2cdd1a7ba7382e7a8ce19f39bc4cab7da1dae/Documents/Example%201.pdf
